# This is a basic workflow to help you get started with Actions

name: CI_Create_Release

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get Hash
        run: FOR /F "tokens=*" %%a in ('git rev-parse --short HEAD') do SET HASH=%%a
        shell: cmd

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: HASH
          release_name: HASH

      - name: Build Package
        run: bz c builds\release-%HASH%.zip Assets .vscode
        shell: cmd

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: builds\release-%HASH%.zip
          asset_name: release-%HASH%.zip
          asset_type: application/zip
